<%@ Page Title="Address" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Address.aspx.cs" Inherits="Coursework1.Address" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <form id="AddressForm" runat="server" style="margin-left:1.5rem" class="was-validated">
        <div>
            <asp:TextBox ID="IDTxt" runat="server" Visible ="false"></asp:TextBox>
        </div>

         <div class="form-group">
            <asp:Label ID="steetNoLbl" runat="server" Text="Street Number"></asp:Label>
            <asp:TextBox ID="streetNoTxt" runat="server" class="form-control" Width="250px" required="required" type="number"></asp:TextBox>
        </div>

         <div class="form-group">
            <asp:Label ID="streetNameLbl" runat="server" Text="Street Name"></asp:Label>
            <asp:TextBox ID="streetNameTxt" runat="server" class="form-control" Width="250px" required="required"></asp:TextBox>
        </div>

         <div class="form-group">
            <asp:Label ID="stateNameLbl" runat="server" Text="State Name"></asp:Label>
            <asp:TextBox ID="stateNameTxt" runat="server" class="form-control" Width="250px" required="required"></asp:TextBox>
        </div>

        <div>
            <asp:Button ID="submitBtn" runat="server" Text="Add" OnClick="SubmitHandler"  class="btn btn-primary form-group"/>
        </div>

        <div>
            <asp:GridView ID="addressGv" runat="server" DataKeyNames="ID" OnRowDataBound="OnRowDataBound"
                OnRowEditing="OnRowEditing" OnRowCancelingEdit="OnRowCancelingEdit" OnRowDeleting="OnRowDeleting"
                EmptyDataText="No records has been added." AutoGenerateEditButton="true" AutoGenerateDeleteButton="true"
                class="table table-bordered table-condensed table-responsive table-hover " />
        </div>

        <div>
            <asp:Button ID="updateBtn" runat="server" Text="Update" OnClick="SubmitHandler" Visible="false" class="btn btn-primary form-group"/>
        </div>
    </form>
</asp:Content>