<%@ Page Title="Teacher" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Teacher.aspx.cs" Inherits="Coursework1.Teacher" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <form id="TeacherForm" runat="server" style="margin-left:1.5rem" class="was-validated">
        <div>
            <asp:TextBox ID="IDTxt" runat="server" Visible ="false"></asp:TextBox>
        </div>


        <div class="form-group">
            <asp:Label ID="nameLbl" runat="server" Text="Name"></asp:Label>
            <asp:TextBox ID="nameTxt" runat="server" class="form-control" Width="250px" required="required"></asp:TextBox>
        </div>

        <div class="form-group">
            <asp:Label ID="emailLbl" runat="server" Text="Email"></asp:Label>
            <asp:TextBox ID="emailTxt" runat="server" class="form-control" Width="250px" type="email" required="required"></asp:TextBox>
        </div>

                <div class="form-group">
            <asp:Label ID="studentIDLbl" runat="server" Text="Student_ID"></asp:Label>
            <%--<asp:TextBox ID="studentIDTxt" runat="server" class="form-control" Width="250px" required="required"></asp:TextBox>--%>
            <asp:DropDownList ID="studentIDDropDown" runat="server" ></asp:DropDownList>
                    <%--<asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" ProviderName="<%$ ConnectionStrings:ConnectionString.ProviderName %>" SelectCommand="SELECT &quot;STUDENT_ID&quot; FROM &quot;STUDENT&quot;"></asp:SqlDataSource>--%>
        </div>

        <div>
            <asp:Button ID="submitBtn" runat="server" Text="Add" OnClick="SubmitHandler"  class="btn btn-primary form-group"/>
            <asp:Label ID="ErrorLbl" runat="server" Text="" Visible="False" style="color:red"></asp:Label>
            <%--<asp:Button ID="formerStudentBtn" runat="server" Text="Former Student" OnClick="StudentHandler"  class="btn btn-primary form-group"/>--%>
        </div>
        <div>
            <asp:GridView ID="teacherGv" runat="server" DataKeyNames="ID" OnRowDataBound="OnRowDataBound"
                OnRowEditing="OnRowEditing" OnRowCancelingEdit="OnRowCancelingEdit"  OnRowDeleting="OnRowDeleting" 
                EmptyDataText="No records has been added." AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" 
                class="table table-bordered table-condensed table-responsive table-hover "/>
        </div>

        <div>
            <asp:Button ID="updateBtn" runat="server" Text="Update" OnClick="SubmitHandler" Visible="false" class="btn btn-primary form-group"/>
        </div>
    </form>
</asp:Content>
